// 種子資料(多語)。L() = {tc,sc,ja,en}
function L(tc, sc, ja, en){ return {tc, sc, ja, en}; }

const exhibition = {
  id: "jfex2026s",
  name: L("JFEX SUMMER 2026 — 日本食品輸出EXPO / JFEX / Food LogiX","JFEX SUMMER 2026 — 日本食品输出EXPO / JFEX / Food LogiX","JFEX SUMMER 2026 —「日本の食品」輸出EXPO / JFEX / Food LogiX","JFEX SUMMER 2026 — Japan Food Export EXPO / JFEX / Food LogiX"),
  date: "2026/6/24–6/26",
  venue: L("東京 Big Sight(東京國際展示場)","东京 Big Sight(东京国际展示场)","東京ビッグサイト","Tokyo Big Sight"),
  organizer: "RX Japan",
  scale: L("約700家參展商・約60國海外買家","约700家参展商・约60国海外买家","約700社出展・約60ヶ国の海外バイヤー","~700 exhibitors · buyers from ~60 countries"),
  status: L("進行中","进行中","開催中","Active")
};

const exhibitors = [
  { id:"e01", booth:"E-12", reviewed:true, status:"approved",
    name:L("靜岡茶園股份有限公司","静冈茶园股份有限公司","静岡茶園株式会社","Shizuoka Tea Garden Co."),
    category:L("飲料・茶","饮料・茶","飲料・茶","Beverages / Tea") },
  { id:"e02", booth:"J-08", reviewed:true, status:"approved",
    name:L("北海道健康食品","北海道健康食品","北海道ヘルスフーズ","Hokkaido Health Foods"),
    category:L("機能性食品・介護食","功能性食品・介护食","機能性食品・介護食","Functional / Care food") },
  { id:"e03", booth:"F-21", reviewed:false, status:"pending",
    name:L("大阪零食工坊","大阪零食工坊","大阪スナック工房","Osaka Snack Works"),
    category:L("加工食品・零食","加工食品・零食","加工食品・スナック","Processed food / Snacks") }
];

const products = [
  { id:"p001", exhibitor_id:"e01", reviewed:true, open_l1:true, open_l2:true,
    name:L("特上 有機抹茶 100g","特上 有机抹茶 100g","特上 有機抹茶 100g","Premium Organic Matcha 100g"),
    consumer:{ image:"🍵",
      story:L("靜岡百年茶園,石臼研磨,色澤翠綠、香氣濃郁。","静冈百年茶园,石臼研磨,色泽翠绿、香气浓郁。","静岡の百年茶園、石臼挽き、鮮やかな緑と豊かな香り。","Century-old Shizuoka garden, stone-milled, vivid green and aromatic."),
      feature:L("有機認證・無添加・適合沖泡與烘焙","有机认证・无添加・适合冲泡与烘焙","有機認証・無添加・飲用と製菓に","Organic, additive-free, for drinking & baking"),
      origin:L("日本・靜岡縣","日本・静冈县","日本・静岡県","Shizuoka, Japan"),
      usage:L("80℃熱水沖泡,或用於甜點烘焙","80℃热水冲泡,或用于甜点烘焙","80℃のお湯で点てる、製菓にも","Brew at 80℃ or use in baking"),
      price:L("參考售價 ¥2,160/罐","参考售价 ¥2,160/罐","参考価格 ¥2,160/缶","Ref. ¥2,160/can"),
      buy:L("官方旗艦店 / 詢問表單","官方旗舰店 / 询问表单","公式ストア / 問合せ","Official store / inquiry") },
    b2b:{ moq:L("100罐","100罐","100缶","100 cans"),
      wholesale:L("¥1,180/罐(未稅)","¥1,180/罐(未税)","¥1,180/缶(税抜)","¥1,180/can (excl. tax)"),
      sample:L("可提供樣品3罐,運費買方負擔","可提供样品3罐,运费买方负担","サンプル3缶可、送料は買主負担","3 samples, buyer pays shipping"),
      exportT:L("可出口台灣/中國大陸,需冷藏物流","可出口台湾/中国大陆,需冷藏物流","台湾/中国へ輸出可、冷蔵物流","Export to TW/CN, needs cold chain"),
      oem:L("支援OEM貼牌,MOQ 500罐起","支持OEM贴牌,MOQ 500罐起","OEM対応、MOQ 500缶~","OEM available, MOQ 500+"),
      adminNote:L("現場試飲品質佳,茶農配合度高;建議台灣高端茶飲通路。","现场试饮品质佳,茶农配合度高;建议台湾高端茶饮通路。","試飲good、茶農の協力的;台湾の高級茶チャネル推奨。","Great tasting on-site, cooperative grower; suits premium TW tea channels."),
      recommend:5, fit_tw:true, fit_cn:true, follow:true },
    admin_meta:{ verbal:L("口頭可談到 ¥1,050/罐(量大)","口头可谈到 ¥1,050/罐(量大)","口頭で¥1,050/缶(大口)","Verbal ¥1,050/can (bulk)"),
      attitude:L("積極,願長期合作","积极,愿长期合作","積極的、長期希望","Eager, wants long-term"),
      risk:L("產量有上限,旺季可能缺貨","产量有上限,旺季可能缺货","生産上限あり、繁忙期欠品の恐れ","Capacity capped, peak shortages"),
      interested:["A","C"] } },
  { id:"p002", exhibitor_id:"e01", reviewed:true, open_l1:true, open_l2:true,
    name:L("深蒸煎茶 茶包","深蒸煎茶 茶包","深蒸し煎茶 ティーバッグ","Deep-steamed Sencha Teabags"),
    consumer:{ image:"🫖",
      story:L("便利茶包,辦公室與居家皆宜。","便利茶包,办公室与居家皆宜。","便利なティーバッグ、オフィスにも家庭にも。","Convenient teabags for office and home."),
      feature:L("三角立體茶包・冷泡熱泡皆可","三角立体茶包・冷泡热泡皆可","三角ティーバッグ・水出し/お湯出し可","Pyramid bags, hot or cold brew"),
      origin:L("日本・靜岡縣","日本・静冈县","日本・静岡県","Shizuoka, Japan"),
      usage:L("冷泡或熱泡均可","冷泡或热泡均可","水出し・お湯出しどちらも","Cold or hot brew"),
      price:L("參考售價 ¥980/盒","参考售价 ¥980/盒","参考価格 ¥980/箱","Ref. ¥980/box"),
      buy:L("官方旗艦店","官方旗舰店","公式ストア","Official store") },
    b2b:{ moq:L("200盒","200盒","200箱","200 boxes"),
      wholesale:L("¥520/盒(未稅)","¥520/盒(未税)","¥520/箱(税抜)","¥520/box (excl. tax)"),
      sample:L("可提供樣品2盒","可提供样品2盒","サンプル2箱可","2 sample boxes"),
      exportT:L("可出口台灣/中國大陸,常溫物流","可出口台湾/中国大陆,常温物流","台湾/中国へ輸出可、常温物流","Export TW/CN, ambient logistics"),
      oem:L("支援ODM客製包裝,MOQ 1000盒","支持ODM定制包装,MOQ 1000盒","ODM包装対応、MOQ 1000箱","ODM packaging, MOQ 1000+"),
      adminNote:L("適合電商通路,單價低、好上架。","适合电商通路,单价低、好上架。","EC向き、単価安く扱いやすい。","Good for e-commerce, low price, easy to list."),
      recommend:4, fit_tw:true, fit_cn:true, follow:true },
    admin_meta:{ verbal:L("¥480/盒(量大)","¥480/盒(量大)","¥480/箱(大口)","¥480/box (bulk)"),
      attitude:L("積極","积极","積極的","Eager"),
      risk:L("無明顯風險","无明显风险","目立つリスクなし","No notable risk"),
      interested:["A","C"] } },
  { id:"p003", exhibitor_id:"e02", reviewed:true, open_l1:true, open_l2:true,
    name:L("軟質介護食 鮭魚粥","软质介护食 鲑鱼粥","やわらか介護食 鮭おかゆ","Soft Care Food: Salmon Porridge"),
    consumer:{ image:"🥣",
      story:L("為長者設計的易嚥營養餐。","为长者设计的易咽营养餐。","高齢者向けの飲み込みやすい栄養食。","Easy-to-swallow nutrition for seniors."),
      feature:L("易吞嚥・高蛋白・常溫保存","易吞咽・高蛋白・常温保存","嚥下対応・高たんぱく・常温保存","Easy swallow, high protein, ambient"),
      origin:L("日本・北海道","日本・北海道","日本・北海道","Hokkaido, Japan"),
      usage:L("隔水加熱即食","隔水加热即食","湯せんで温めて","Warm in water bath, ready to eat"),
      price:L("參考售價 ¥380/份","参考售价 ¥380/份","参考価格 ¥380/食","Ref. ¥380/serving"),
      buy:L("詢問表單","询问表单","問合せ","Inquiry") },
    b2b:{ moq:L("500份","500份","500食","500 servings"),
      wholesale:L("¥210/份(未稅)","¥210/份(未税)","¥210/食(税抜)","¥210/serving (excl. tax)"),
      sample:L("可提供樣品5份","可提供样品5份","サンプル5食可","5 samples"),
      exportT:L("可出口台灣/中國大陸,需食品標示翻譯","可出口台湾/中国大陆,需食品标示翻译","台湾/中国へ輸出可、食品表示の翻訳要","Export TW/CN, label translation needed"),
      oem:L("支援OEM,MOQ 2000份","支持OEM,MOQ 2000份","OEM対応、MOQ 2000食","OEM available, MOQ 2000+"),
      adminNote:L("HACCP認證齊全,適合介護機構與醫療通路。","HACCP认证齐全,适合介护机构与医疗通路。","HACCP取得済、介護施設・医療チャネル向き。","HACCP certified, suits care/medical channels."),
      recommend:5, fit_tw:true, fit_cn:true, follow:true },
    admin_meta:{ verbal:L("¥190/份(年約)","¥190/份(年约)","¥190/食(年契約)","¥190/serving (annual)"),
      attitude:L("非常積極,有意設台灣總代理","非常积极,有意设台湾总代理","非常に積極的、台湾総代理を希望","Very eager, wants TW master agency"),
      risk:L("需確認進口食品法規","需确认进口食品法规","輸入食品規制の確認要","Verify import food regulations"),
      interested:["B"] } },
  { id:"p004", exhibitor_id:"e02", reviewed:true, open_l1:true, open_l2:true,
    name:L("長者營養果凍","长者营养果冻","高齢者向け 栄養ゼリー","Senior Nutrition Jelly"),
    consumer:{ image:"🍮",
      story:L("一口補充營養的果凍。","一口补充营养的果冻。","一口で栄養補給できるゼリー。","A jelly that delivers nutrition in one bite."),
      feature:L("高熱量・好入口・多口味","高热量・好入口・多口味","高カロリー・食べやすい・多味","High calorie, easy to eat, many flavors"),
      origin:L("日本・北海道","日本・北海道","日本・北海道","Hokkaido, Japan"),
      usage:L("開封即食","开封即食","開封してそのまま","Open and eat"),
      price:L("參考售價 ¥150/個","参考售价 ¥150/个","参考価格 ¥150/個","Ref. ¥150/each"),
      buy:L("詢問表單","询问表单","問合せ","Inquiry") },
    b2b:{ moq:L("1000個","1000个","1000個","1000 units"),
      wholesale:L("¥78/個(未稅)","¥78/个(未税)","¥78/個(税抜)","¥78/unit (excl. tax)"),
      sample:L("可提供樣品一組6入","可提供样品一组6入","サンプル6個入1組可","1 sample pack of 6"),
      exportT:L("可出口台灣/中國大陸","可出口台湾/中国大陆","台湾/中国へ輸出可","Export to TW/CN"),
      oem:L("支援ODM口味客製,MOQ 5000個","支持ODM口味定制,MOQ 5000个","ODM味カスタム対応、MOQ 5000個","ODM flavor custom, MOQ 5000+"),
      adminNote:L("毛利高,適合介護與電商雙通路。","毛利高,适合介护与电商双通路。","粗利高、介護とECの両チャネル向き。","High margin, suits care + e-commerce."),
      recommend:4, fit_tw:true, fit_cn:true, follow:true },
    admin_meta:{ verbal:L("¥70/個(量大)","¥70/个(量大)","¥70/個(大口)","¥70/unit (bulk)"),
      attitude:L("積極","积极","積極的","Eager"),
      risk:L("冷鏈非必要,常溫即可","冷链非必要,常温即可","冷蔵不要、常温で可","No cold chain needed"),
      interested:["B","C"] } },
  { id:"p005", exhibitor_id:"e03", reviewed:false, open_l1:true, open_l2:false,
    name:L("醬油仙貝禮盒","酱油仙贝礼盒","醤油せんべい 詰合せ","Soy-sauce Senbei Gift Box"),
    consumer:{ image:"🍘",
      story:L("傳統炭烤醬油仙貝。","传统炭烤酱油仙贝。","伝統の炭火焼き醤油せんべい。","Traditional charcoal-grilled soy senbei."),
      feature:L("炭烤香氣・酥脆・送禮自用兩相宜","炭烤香气・酥脆・送礼自用两相宜","炭火の香ばしさ・サクサク・贈答にも","Charcoal aroma, crisp, great for gifts"),
      origin:L("日本・大阪","日本・大阪","日本・大阪","Osaka, Japan"),
      usage:L("開封即食","开封即食","開封してそのまま","Open and eat"),
      price:L("參考售價 ¥1,080/盒","参考售价 ¥1,080/盒","参考価格 ¥1,080/箱","Ref. ¥1,080/box"),
      buy:L("官方旗艦店","官方旗舰店","公式ストア","Official store") },
    b2b:{ moq:L("100盒","100盒","100箱","100 boxes"),
      wholesale:L("¥560/盒(未稅)","¥560/盒(未税)","¥560/箱(税抜)","¥560/box (excl. tax)"),
      sample:L("可提供樣品2盒","可提供样品2盒","サンプル2箱可","2 sample boxes"),
      exportT:L("可出口台灣/中國大陸,常溫物流","可出口台湾/中国大陆,常温物流","台湾/中国へ輸出可、常温物流","Export TW/CN, ambient logistics"),
      oem:L("OEM/ODM皆可,小批量對應,MOQ 300盒","OEM/ODM皆可,小批量对应,MOQ 300盒","OEM/ODM可、小ロット対応、MOQ 300箱","OEM/ODM ok, small lots, MOQ 300+"),
      adminNote:L("小批量友善,適合新進口商試單。","小批量友善,适合新进口商试单。","小ロット可、新規輸入業者の試し買い向き。","Small-lot friendly, good for new importers' trial."),
      recommend:3, fit_tw:true, fit_cn:true, follow:false },
    admin_meta:{ verbal:L("¥520/盒","¥520/盒","¥520/箱","¥520/box"),
      attitude:L("一般","一般","普通","Neutral"),
      risk:L("資料尚未審核完成","资料尚未审核完成","データ未審査","Data not yet reviewed"),
      interested:["A","C"] } }
];

// L4 指定客戶授權:client_id → 可見商品
const grants = [
  { client_id:"A", product_id:"p001" }, { client_id:"A", product_id:"p002" }, { client_id:"A", product_id:"p005" },
  { client_id:"B", product_id:"p003" }, { client_id:"B", product_id:"p004" },
  { client_id:"C", product_id:"p001" }, { client_id:"C", product_id:"p002" }, { client_id:"C", product_id:"p004" }, { client_id:"C", product_id:"p005" }
];

module.exports = { exhibition, exhibitors, products, grants };
